const DLList = require('./DLList')

let cities = new DLList()
cities.insert('Conway', 'head')
cities.insert('Russellville', 'Conway')
cities.insert('Carlisle', 'Russellville')
cities.insert('Alma', 'Carlisle')
cities.display()
console.log()
cities.remove('Alma')
cities.display()
console.log()
cities.dispReverse()
